export const mockTweet = {
  "_type": "snscrape.modules.twitter.Tweet",
  "cashtags": null,
  "content": "Gn 🙏 ",
  "conversationId": 1448458010179866628,
  "coordinates": null,
  "date": "2021-10-14T01:17:55+00:00",
  "hashtags": null,
  "id": 1448458010179866628,
  "inReplyToTweetId": null,
  "inReplyToUser": null,
  "lang": "und",
  "likeCount": 8,
  "media": [
    {
      "_type": "snscrape.modules.twitter.Photo",
      "fullUrl": "https://pbs.twimg.com/media/FBn04l-WUAIk4VD?format=jpg&name=large",
      "previewUrl": "https://pbs.twimg.com/media/FBn04l-WUAIk4VD?format=jpg&name=small"
    }
  ],
  "mentionedUsers": null,
  "outlinks": null,
  "place": null,
  "quoteCount": 0,
  "quotedTweet": null,
  "renderedContent": "Gn 🙏 https://t.co/KoFGEIvOM7",
  "replyCount": 1,
  "retweetCount": 0,
  "retweetedTweet": null,
  "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
  "sourceLabel": "Twitter for Android",
  "sourceUrl": "http://twitter.com/download/android",
  "tcooutlinks": null,
  "url": "https://twitter.com/Seranged/status/1448458010179866628",
  "user": {
    "_type": "snscrape.modules.twitter.User",
    "created": "2012-10-21T15:38:52+00:00",
    "description": "Product of @Twicrates (Produced via Neural Nets) @Boobahub\nBuilding @pentaclexyz pentacle.xyz\nBuilding @combatcurve combatcurve.com\nBuilding @chess_mafia",
    "descriptionUrls": [
      {
        "indices": [
          81,
          104
        ],
        "tcourl": "https://t.co/46JFRHIx6x",
        "text": "pentacle.xyz",
        "url": "http://pentacle.xyz"
      },
      {
        "indices": [
          127,
          150
        ],
        "tcourl": "https://t.co/rpwdMQVW4E",
        "text": "combatcurve.com",
        "url": "http://combatcurve.com"
      }
    ],
    "displayname": "Seranged (Bread #8)",
    "favouritesCount": 114709,
    "followersCount": 2311,
    "friendsCount": 512,
    "id": 895594286,
    "label": null,
    "linkTcourl": null,
    "linkUrl": null,
    "listedCount": 30,
    "location": "The Cloud ",
    "mediaCount": 7055,
    "profileBannerUrl": "https://pbs.twimg.com/profile_banners/895594286/1630878228",
    "profileImageUrl": "https://pbs.twimg.com/profile_images/1440016807558008834/bhSzHv0U_normal.png",
    "protected": false,
    "rawDescription": "Product of @Twicrates (Produced via Neural Nets) @Boobahub\nBuilding @pentaclexyz https://t.co/46JFRHIx6x\nBuilding @combatcurve https://t.co/rpwdMQVW4E\nBuilding @chess_mafia",
    "statusesCount": 25624,
    "url": "https://twitter.com/Seranged",
    "username": "Seranged",
    "verified": false
  }
}
  export const mockTweetWithPhotos = {
    "_type": "snscrape.modules.twitter.Tweet",
    "cashtags": null,
    "content": "code is a bit like love and death",
    "conversationId": 1449858128686768129,
    "coordinates": null,
    "date": "2021-10-17T22:01:29+00:00",
    "hashtags": null,
    "id": 1449858128686768129,
    "inReplyToTweetId": null,
    "inReplyToUser": null,
    "lang": "en",
    "likeCount": 47,
    "media": null,
    "mentionedUsers": null,
    "outlinks": null,
    "place": null,
    "quoteCount": 1,
    "quotedTweet": null,
    "renderedContent": "code is a bit like love and death",
    "replyCount": 4,
    "retweetCount": 4,
    "retweetedTweet": null,
    "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
    "sourceLabel": "Twitter Web App",
    "sourceUrl": "https://mobile.twitter.com",
    "tcooutlinks": null,
    "url": "https://twitter.com/pentcle/status/1449858128686768129",
    "user": {
      "_type": "snscrape.modules.twitter.User",
      "created": "2017-04-10T19:51:54+00:00",
      "description": "",
      "descriptionUrls": null,
      "displayname": "pentacle",
      "favouritesCount": 30692,
      "followersCount": 2992,
      "friendsCount": 644,
      "id": 851523151129333765,
      "label": null,
      "linkTcourl": "https://t.co/mxxF1jJyX0",
      "linkUrl": "http://pentacle.xyz/",
      "listedCount": 69,
      "location": "",
      "mediaCount": 379,
      "profileBannerUrl": "https://pbs.twimg.com/profile_banners/851523151129333765/1634419049",
      "profileImageUrl": "https://pbs.twimg.com/profile_images/1449484658962534406/X8Aob5Z1_normal.jpg",
      "protected": false,
      "rawDescription": "",
      "statusesCount": 3324,
      "url": "https://twitter.com/pentcle",
      "username": "pentcle",
      "verified": false
    }
  }
